version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/your_db_name
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=your_db_name
    ports:
      - "5432:5432"

volumes:
  postgres_data: