# Generated by Django 4.2.18 on 2025-02-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='propertyphoto',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertystatus',
            name='property',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyPhoto',
        ),
        migrations.DeleteModel(
            name='PropertyStatus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
